training_reg/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.user_logout, name="logout"),
]

training_reg/training/urls.py
from django.urls import path
from training import views

app_name = "training"

urlpatterns = [
    path("", views.home, name="home"),
    path("courses/", views.get_courses, name="get_courses"),
    path("courses/<str:course_name>/details/", views.get_course_details, name="get_course_detail"),
    path("courses/enroll/", views.create_user_course, name="create_user_course"),
    path("user/courses/registered/", views.user_registered_courses, name="user_registered_courses"),
    path("courses/<str:student_id>/<str:course_name>/quit/", views.quit_course, name="quit_course"),
    path("student/profile/", views.get_profile_info, name="get_profile_info"),
]

training_reg/training_reg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("training.urls", namespace="training")),
    path("", include("dashboard.urls", namespace="dashboard")),
]

training_reg/training/models.py
from django.db import models
from accounts.models import *
# Create your models here.




class TrainingProvider(models.Model):
    department = models.ForeignKey(Department, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=255) # company name

    def __str__(self):
        return self.name


class Course(models.Model):
    COURSE_PERIODS = (
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
    )

    provider = models.ForeignKey(TrainingProvider, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=255)
    brief = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField(null=True)
    period = models.CharField(max_length=255, choices=COURSE_PERIODS)
    available = models.BooleanField(default=False, null=True)
    max_student_numbers = models.IntegerField(null=True, default=100)


    @property
    def get_course_registered_students(self):
        course_register_details = self.usercourse_set.all()
        registered_students = course_register_details.count()
        return registered_students

    @property
    def get_course_seats_left(self):
        course_register_details = self.usercourse_set.all()
        registered_students = course_register_details.count()
        seats_left = self.max_student_numbers - registered_students
        if seats_left == 0:
            self.available = False

        return seats_left

    def __str__(self):
        return self.name

class UserCourse(models.Model):
    course = models.ForeignKey(Course, null=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    course_pass = models.BooleanField(default=None, null=True, blank=True)

    def __str__(self):
        return f"[ Course: {self.course.name} ] [ Username: {self.user.username} ] [ Pass Status: {self.course_pass} ]"

training_reg/training/views.py
from django.contrib import auth
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from training.models import *
import json
from django.http import JsonResponse

# Create your views here.
def home(request):
    return render(request, "training/home.html")


def get_courses(request):
    courses = Course.objects.filter(provider__department=request.user.department)
    context = {"courses":courses}
    return render(request, "training/courses_list.html", context)



def get_course_details(request, course_name):
    course = Course.objects.get(name__icontains=course_name)
    context = {"course": course}
    return render(request, "training/course_detail.html", context)


@login_required(login_url="accounts:login")
def create_user_course(request):
    data = json.loads(request.body)
    student_id = data["user_id"]
    course_name = data["course_name"]
    student = User.objects.get(id=student_id)
    course = Course.objects.get(name__icontains=course_name)
    if student.count_trainings != 2:
        if not UserCourse.objects.filter(user=student, course=course).exists():
            student_course = UserCourse.objects.create(user=student, course=course)
            student.count_trainings += 1
            student.save()
            student_course.save()
            return JsonResponse(student.count_trainings, safe=False)
        else:
            response = None
            return JsonResponse(response, safe=False)
    else:
        response = False
        return JsonResponse(response, safe=False)


@login_required(login_url="accounts:login")
def user_registered_courses(request):
    user_courses = UserCourse.objects.filter(user=request.user)
    context = {"user_courses":user_courses}
    return render(request, "training/user_registered_courses.html", context)


@login_required(login_url="accounts:login")
def quit_course(request, student_id, course_name):
    if request.method == "POST":
        student = User.objects.get(id=student_id)
        course = Course.objects.get(name__icontains=course_name)
        user_course = UserCourse.objects.get(user=student, course=course)
        if user_course.course_pass == None:
            user_course.delete()
            student.count_trainings -= 1
            student.save()
            return redirect("training:user_registered_courses")
        else:
            messages.error(request, "You cannot quit a course that you had already finished!")
            return redirect("training:user_registered_courses")
    else:
        context = {"course_name":course_name}
        return render(request, "training/quit_course.html", context)


@login_required(login_url="accounts:login")
def get_profile_info(request):
    return render(request, "training/profile.html")

training_reg/training/templates/training/course_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3">

            </div>
            <div class="col-sm-6 course_detail">
                <h1 style="padding:10px;text-align: center;border-bottom: 1px solid;border-top: 1px solid">{{ course.name }}</h1>
                <br><br><br>
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Company</th>
                      <th scope="col">Status</th>
                      <th scope="col">Period</th>
                      <th scope="col">Start Date</th>
                      <th scope="col">End Date</th>
                      <th scope="col">Registered Students</th>
                      <th scope="col">Seats Left</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>{{ course.provider }}</td>
                      <td>
                          {% if course.available %}
                              <span class="badge bg-success">Available</span>
                          {% else %}
                              <span class="badge bg-danger">Closed</span>
                          {% endif %}
                      </td>
                        <td>{{ course.period }}</td>
                        <td>{{ course.start_date }}</td>
                        <td>{{ course.end_date }}</td>
                        <td>{{ course.get_course_registered_students }}</td>
                        <td>{{ course.get_course_seats_left }}</td>
                    </tr>

                  </tbody>
                </table>
                <p class="text-center">
                  <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Show Brief
                  </button>
                </p>
                <div class="collapse" id="collapseExample">
                  <div class="card card-body" style="text-align: left">
                        <pre>{{ course.brief }}</pre>
                  </div>
                </div>
                <div style="margin-top:50px;" class="text-center">
                        {% if user.is_authenticated %}
                            {% if course.get_course_seats_left > 0 and user.count_trainings < 2 and user.count_trainings >= 0 %}
                                <button id="enroll" class="btn btn-success" onclick="enroll('{{ user.id }}', '{{ course.name }}')">Enroll</button>
                            {% endif %}
                      {% endif %}
                </div>
            </div>
            <div class="col-sm-3">

            </div>
        </div>
    </div>
    <script>
        function enroll(student_id, course_name){
            let url = "../../enroll/";
            fetch(url, {
                method: "POST",
                headers: {
                    "Content-type": "application/json",
                    "X-CSRFToken": csrftoken,
                },
                body: JSON.stringify({"course_name":course_name, "user_id":student_id}),
                })
                .then((response) => {
                    return response.json();
                })
                .then((data) => {
                    console.log(`Data: ${data}`)
                    if(data == false){
                        alert("You can't register more than 2 trainings, if you failed in one, contact instructor to let you retake or register a training.")
                    }
                    else if(data == null){
                        alert("You already registered this course.")
                    }
                    else{
                        total_user_registered_courses = document.getElementById("courses-total");
                        total_user_registered_courses.innerHTML = data
                    }
                })
            }

    </script>
{% endblock %}

training_reg/training/templates/training/courses_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>

        .headers{
            color:#96292E;
            font-weight: bolder;
        }
    </style>
    <div class="container-fluid" style="margin-top: 60px">
        <div class="row">
            {% for course in courses %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <div class="card text-dark bg-light mb-3" style="max-width: 40rem;">
                  <div class="card-header"><p class="head_colors"><span class="headers">Name:</span> {{ course.name }}</p></div>
                  <div class="card-header"><p class="head_colors"><span class="headers">Provider:</span> {{ course.provider.name }}</p></div>
                    <div class="card-header"><p class="head_colors"><span class="headers">Status:</span>
                      {% if course.available %}
                          <span class="badge bg-success">Available</span>
                      {% else %}
                          <span class="badge bg-danger">Closed</span>
                      {% endif %}
                  </p></div>

                  <div class="card-header"><p class="head_colors"><span class="headers">Maximum students:</span> {{ course.max_student_numbers }}</p></div>
                  <div class="card-header"><p class="head_colors"><span class="headers">Seats Left:</span> {{ course.get_course_seats_left }}</p></div>
                  <div class="card-body" >
                    <h5 class="card-title head_colors headers">Brief</h5>
                    <pre class="card-text head_colors" style="text-align: justify">{{ course.brief }}</pre>
                  </div>
                  <div class="card-header">
                      {% if user.is_authenticated %}
                            {% if course.get_course_seats_left > 0 %}
                                <button id="enroll" class="btn btn-success" onclick="enroll('{{ user.id }}', '{{ course.name }}')">Enroll</button>
                            {% endif %}
                      {% endif %}
                      <a class="btn btn-secondary" href="{% url 'training:get_course_detail' course_name=course.name %}">Course Details</a>
                  </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <script src="{% static 'js/training/student_enrolls.js' %}">

    </script>
{% endblock %}

training_reg/training/templates/training/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <div class="container home_body" style="max-height: 100%">
        <h2 class="home_text_spacing">Want to always feel fair and helpful about your university trainings?</h2>
        <h3 class="home_text_spacing">Come on, and Join Us!</h3>
        <img  class="navbar-brand img-responsive img-responsive edit home_text_spacing" src="{% static 'icons/academy_logo.ico' %}" alt="Brand icon">

        <h4 class="home_text_spacing">“Learn as if you were not reaching your goal and as though you were scared of missing it”</h4>






    </div>
        <div style="height: 212px"></div>
    <!-- Footer -->
        <footer class="page-footer font-small stylish-color-dark pt-4">

          <!-- Footer Links -->
          <div class="container text-center text-md-left">

            <!-- Grid row -->
            <div class="row">
                <div class="col-md-4 mx-auto ">
                    <img class="navbar-brand img-responsive img-responsive edit" src="{% static 'images/logo.png' %}" alt="Brand icon">
                    <pre class="footer_text_color">El-Hadaba El-Wosta-Elmokattam
        - Close to Mokattam Central2 </pre>
                </div>
              <!-- Grid column -->
              <div class="col-md-4 mx-auto ">

                <!-- Content -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4 footer_text_color">Contact Us</h5>
                <p class="footer_text_color">Phone: <span>19049</span></p>
                  <p class="footer_text_color">Email: <span>info@eng.modern-academy.edu.eg</span></p>

              </div>
              <!-- Grid column -->


              <!-- Grid column -->
              <div class="col-md-4 mx-auto">

                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4 footer_text_color">Links</h5>

                <ul class="list-unstyled">
                  <li>
                    <a class="footer_text_color active" href="http://www.modern-academy.edu.eg/">MA Computer Science</a>
                  </li>
                  <li>
                    <a class="footer_text_color active"  href="http://eng.modern-academy.edu.eg/">MA Engineering</a>
                  </li>
                  <li>
                    <a class="footer_text_color active"  href="https://eng.synceg.net/">MA Moodle</a>
                  </li>
                </ul>

              </div>
              <!-- Grid column -->

            </div>
            <!-- Grid row -->

          </div>
          <!-- Footer Links -->

        </footer>
        <!-- Footer -->
{% endblock %}

training_reg/training/templates/training/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>

        .headers{
            color:#96292E;
            font-weight: bolder;
        }
    </style>
    <div class="container-fluid" style="margin-top: 60px">
        <div style="margin: auto">
            <div class="card text-dark bg-light mb-12" style="max-width: 40rem;margin: auto">
              <div class="card-header"><p class="head_colors"><span class="headers">ID:</span> {{ user.id }} </p></div>
              <div class="card-header"><p class="head_colors"><span class="headers">Name:</span> {{ user.first_name }} {{ user.last_name }} {{ user.family_name }}</p></div>
              <div class="card-header"><p class="head_colors"><span class="headers">Username:</span> {{ user.username }}</p></div>

              <div class="card-header"><p class="head_colors"><span class="headers">Email Address:</span> {{ user.email }}</p></div>
              <div class="card-header"><p class="head_colors"><span class="headers">Department:</span> {{ user.department }}</p></div>
              <div class="card-header"><p class="head_colors"><span class="headers">Registered Trainings: </span> {{ user.count_trainings }}</p></div>
            </div>
        </div>
    </div>
{% endblock %}

training_reg/training/templates/training/quit_course.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1 style="padding:10px">Are you sure you want to quit your '{{ course_name }}' course?</h1>
    <form method="POST">
        {% csrf_token %}
        <a class="btn btn-secondary" href="{% url 'training:user_registered_courses' %}">Cancel</a>
        <input class="btn btn-danger" value="Quit" type="submit">

    </form>
    {% include 'messages.html' %}
    </div>
{% endblock %}

training_reg/training/templates/training/user_registered_courses.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>

        .headers{
            color:#96292E;
            font-weight: bolder;
        }
    </style>
    <div class="container-fluid" style="margin-top: 60px">
        <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Course</th>
                      <th scope="col">Company</th>
                      <th scope="col">Status</th>
                      <th scope="col">Period</th>
                      <th scope="col">Start Date</th>
                      <th scope="col">End Date</th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for user_course in user_courses %}
                    <tr>
                      <td>{{ user_course.course.name }}</td>
                      <td>{{ user_course.course.provider }}</td>
                      <td>
                    {% if user_course.course_pass == None %}
                          <span class="badge bg-warning">Enrolled</span>

                      {% elif not user_course.course_pass %}
                              <span class="badge bg-danger">Failed</span>

                      {% else %}
                          <span class="badge bg-success">Passed</span>
                      {% endif %}
                      </td>
                        <td>{{ user_course.course.period }}</td>
                        <td>{{ user_course.course.start_date }}</td>
                        <td colspan="2">{{ user_course.course.end_date }}</td>
                        <td><a class="btn btn-danger" href="{% url 'training:quit_course' student_id=request.user.id course_name=user_course.course.name %}">Quit</a></td>
                        <td><a class="btn btn-secondary" href="{% url 'training:get_course_detail' course_name=user_course.course.name %}">Show Course</a></td>

                    </tr>

                  {% endfor %}
                  </tbody>
                </table>
            </div>
            <div class="col-sm-3"></div>
        </div>
    </div>
{% endblock %}