training_reg/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.user_logout, name="logout"),
]

training_reg/training/urls.py
from django.urls import path
from training import views

app_name = "training"

urlpatterns = [
    path("", views.home, name="home"),
    path("courses/", views.get_courses, name="get_courses"),
    path("courses/<str:course_name>/details/", views.get_course_details, name="get_course_detail"),
    path("courses/enroll/", views.create_user_course, name="create_user_course"),
    path("user/courses/registered/", views.user_registered_courses, name="user_registered_courses"),
    path("courses/<str:student_id>/<str:course_name>/quit/", views.quit_course, name="quit_course"),
    path("student/profile/", views.get_profile_info, name="get_profile_info"),
]

training_reg/training_reg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("training.urls", namespace="training")),
    path("", include("dashboard.urls", namespace="dashboard")),
]

training_reg/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Book Store</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


   <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

      <link rel="stylesheet" href="{% static 'css/base.css' %}">

      <script>
          function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getCookie('csrftoken');
      </script>
  </head>
  <body>
    <div class="container-fluid" >
      <nav class="navbar navbar-expand-lg  ">
        <div class="container-fluid">
            <a href="{% url 'training:home' %}">
                <img class="navbar-brand img-responsive img-responsive edit" src="{% static 'icons/academy_logo.ico' %}" alt="Brand icon">
            </a>

          <button style="color:#96292E;" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
            </svg>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item" >
                <a class="nav-link active home_text_color" aria-current="page" href="{% url 'training:home' %}">Home</a>
              </li>
                <li class="nav-item" >
                <a class="nav-link active home_text_color" aria-current="page" href="{% url 'training:get_courses' %}">Courses</a>
              </li>


            </ul>



              <ul class="nav navbar-nav navbar-right" style="margin-right: 60px">
                  {% if user.is_authenticated %}
                      <li class="nav-item">
                        <a class="nav-link home_text_color active" href="{% url 'training:user_registered_courses' %}">My Courses<span id="courses-total">{{ user.count_trainings }}</span></a>
                      </li>
                      <li class="nav-item "><a class="nav-link home_text_color active" href="{% url 'training:get_profile_info' %}">Profile</a></li>
                      <li class="nav-item">
                        <form method="POST" action="{% url 'accounts:logout' %}">
                                  {% csrf_token %}
                                <input class="nav-link home_text_color active" style="border: none;background-color: white" type="submit" value="Logout" >
                          </form>
                      </li>
                          {% else %}
                              <li class="nav-item">
                                <a class="nav-link active home_text_color" href="{% url 'accounts:login' %}">Login</a>
                              </li>
                              <li class="nav-item">
                                <a class="nav-link active home_text_color" href="{% url 'accounts:register' %}">Register</a>
                              </li>
                          {% endif %}
                      <!-- <li class="nav-item">
                        <a class="nav-link disabled " href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                      </li> -->
                    </ul>
                  </div>
                </div>
              </nav>

    </div>

    <div class="container-fluid" style="width:auto">
        {% block content %}
        {% endblock %}
    </div>

  </body>
</html>

training_reg/templates/messages.html
{% load static %}
{% if messages %}
    {% for message in messages %}
        {% if message.tags == "error" %}
            <div class="alert alert-danger alert-dismissible fade show" style="margin: auto;width: auto;" role="alert">
              <img src="{% static 'images/danger-alert.png' %}" alt="Danger Alert." width="20px">
              <strong>{{ message }}</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

        {% else %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" style="margin: auto;width:1000px;" role="alert">
              <strong>{{ message }}</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}