training_reg/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.user_logout, name="logout"),
]

training_reg/dashboard/urls.py
from django.urls import path
from dashboard import views


app_name = "dashboard"

urlpatterns = [
    # Queries Links
    path("dashboard/", views.dashboard_lists, name="dashboard_lists"),
    path("dashboard/<str:company_name>/courses/", views.get_company_courses, name="company_courses"),
    path("dashboard/course/<str:course_name>/", views.get_course_details, name="course_detail"),
    path("dashboard/<str:course_name>/registered_students/", views.get_course_registered_students, name="get_course_registered_students"),
    path("dashboard/training/get_student_training_pass_status/", views.get_student_training_pass_status, name="get_student_training_pass_status"),
    path("dashboard/<str:department_name>/companies/", views.get_department_companies, name="get_department_companies"),
    path("dashboard/<str:department_name>/students/", views.get_department_students, name="get_department_students"),



    # Forms
    path("dashboard/add_company/", views.add_company, name="add_company"),
    path("dashboard/add_course/", views.add_course, name="add_course"),
    path("dashboard/add_new_department/", views.add_new_department, name="add_new_department"),
    path("dashboard/add_student_to_course/", views.add_student_to_course, name="add_student_to_course"),


    # Editing and Deletion

    # Deletion
    path("dashboard/company/<str:company_name>/delete/", views.delete_company, name="delete_company"),
    path("dashboard/course/<str:course_name>/delete/", views.delete_course, name="delete_course"),
    path("dashboard/department/<str:department_name>/delete/", views.delete_department, name="delete_department"),
    path("dashboard/student_course/<int:student_id>/<str:course_name>/delete/", views.delete_student_from_course, name="delete_student_from_course"),

    # Editing
    path("dashboard/course/<str:course_name>/edit/", views.edit_course, name="edit_course"),
    path("dashboard/department/<str:department_name>/edit/", views.edit_department, name="edit_department"),
    path("dashboard/student_course/<int:student_id>/<str:course_name>/edit/", views.edit_student_course, name="edit_student_course"),
    path("dashboard/department/student/<int:student_id>/edit/", views.edit_student_department, name="edit_student_department"),


]

training_reg/training_reg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("training.urls", namespace="training")),
    path("", include("dashboard.urls", namespace="dashboard")),
]

training_reg/dashboard/models.py
from django.db import models

# Create your models here.

training_reg/dashboard/forms.py
from django import forms
from accounts.models import *
from training.models import *
from django.conf import settings

class NewCompanyForm(forms.ModelForm):
    class Meta:
        model = TrainingProvider
        fields = "__all__"

class NewCourseForm(forms.ModelForm):
    start_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.SelectDateWidget)
    end_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.SelectDateWidget)
    class Meta:
        model = Course
        exclude = ["student_numbers"]

class NewStudentToCourseForm(forms.ModelForm):
    class Meta:
        model = UserCourse
        fields = "__all__"

class NewDepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ["name"]

class EditStudentDepartmentForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "family_name", "username", "department", "count_trainings"]

training_reg/dashboard/views.py
from django.shortcuts import render, redirect
from training.models import *
from accounts.models import *
import json
from django.http import JsonResponse
from dashboard.forms import *
from django.contrib import messages
from dashboard.decorators import admin_only


# Create your views here.


################################################################################
# Data Editing and Deletion
############################

# Deletion
@admin_only
def delete_company(request, company_name):
    if request.method == "POST":
        company = TrainingProvider.objects.get(name__icontains=company_name)
        company.delete()
        return redirect("dashboard:dashboard_lists")
    else:
        context = {"company_name": company_name}
        return render(request, "dashboard/Data_Edit_Deletion/delete_company.html", context)


@admin_only
def delete_course(request, course_name):
    if request.method == "POST":
        course = Course.objects.get(name__icontains=course_name)
        course.delete()
        return redirect("dashboard:dashboard_lists")
    else:
        context = {"course_name": course_name}
        return render(request, "dashboard/Data_Edit_Deletion/delete_course.html", context)


@admin_only
def delete_department(request, department_name):
    if request.method == "POST":
        department = Department.objects.get(name__icontains=department_name)
        department.delete()
        return redirect("dashboard:dashboard_lists")
    else:
        context = {"department_name": department_name}
        return render(request, "dashboard/Data_Edit_Deletion/delete_department.html", context)


@admin_only
def delete_student_from_course(request, student_id, course_name):
    student = User.objects.get(id=student_id)
    if request.method == "POST":
        the_course = Course.objects.get(name__icontains=course_name)
        student_in_this_course = UserCourse.objects.get(user=student, course=the_course)
        student_in_this_course.delete()
        return redirect("dashboard:dashboard_lists")
    else:
        context = {"student_name": student.first_name + " " + student.last_name + " " + student.family_name,
                   "course_name": course_name}
        return render(request, "dashboard/Data_Edit_Deletion/delete_student_from_course.html", context)


# Edition
@admin_only
def edit_course(request, course_name):
    course = Course.objects.get(name__icontains=course_name)
    edit_course_form = NewCourseForm(instance=course)
    if request.method == "POST":
        edit_course_form = NewCourseForm(request.POST, instance=course)
        if edit_course_form.is_valid():
            edit_course_form.save()
            messages.success(request, "Course details have been successfully updated.")
            return redirect("dashboard:course_detail", course_name=course_name)
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:add_company")
    else:
        context = {"edit_course_form": edit_course_form, "course_name": course_name}
        return render(request, "dashboard/Data_Edit_Deletion/edit_course.html", context)


@admin_only
def edit_department(request, department_name):
    department = Department.objects.get(name__icontains=department_name)
    edit_department_form = NewDepartmentForm(instance=department)
    if request.method == "POST":
        edit_department_form = NewDepartmentForm(request.POST, instance=department)
        if edit_department_form.is_valid():
            edit_department_form.save()
            messages.success(request, "Course details have been successfully updated.")
            return redirect("dashboard:edit_department", department_name=department_name)
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("/")
    else:
        context = {"edit_department_form": edit_department_form, "department_name": department_name}
        return render(request, "dashboard/Data_Edit_Deletion/edit_department.html", context)


@admin_only
def edit_student_course(request, student_id, course_name):
    student = User.objects.get(id=student_id)
    course = Course.objects.get(name__icontains=course_name)
    student_course = UserCourse.objects.get(user=student, course=course)
    student_course_form = NewStudentToCourseForm(instance=student_course)
    if request.method == "POST":
        student_course_form = NewStudentToCourseForm(request.POST, instance=student_course)
        if student_course_form.is_valid():
            student_course_form.save()
            messages.success(request, "Course details have been successfully updated.")
            return redirect("dashboard:get_course_registered_students", course_name=course_name)
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:get_course_registered_students", course_name=course_name)
    else:
        context = {"student_course_form": student_course_form,
                   "student_name": student.first_name + " " + student.last_name + " " + student.family_name,
                   "course_name": course_name}
        return render(request, "dashboard/Data_Edit_Deletion/edit_student_course.html", context)


@admin_only
def edit_student_department(request, student_id):
    student = User.objects.get(id=student_id)
    user_department_form = EditStudentDepartmentForm(instance=student)
    if request.method == "POST":
        user_department_form = EditStudentDepartmentForm(request.POST, instance=student)
        if user_department_form.is_valid():
            user_department_form.save()
            messages.success(request, "Student data have been successfully updated.")
            return redirect("dashboard:dashboard_lists")
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:dashboard_lists")

    else:
        context = {"user_department_form": user_department_form,
                   "student_name": student.first_name + " " + student.last_name + " " + student.family_name}
        return render(request, "dashboard/Data_Edit_Deletion/edit_user_department.html", context)


##################################################################################
# Creation Forms:
#################
@admin_only
def add_company(request):
    company_add_form = NewCompanyForm()
    if request.method == "POST":
        company_add_form = NewCompanyForm(request.POST)
        if company_add_form.is_valid():
            company_add_form.save()
            messages.success(request, "Company has been successfully added.")
            return redirect("dashboard:add_company")
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:add_company")
    else:
        context = {"company_add_form": company_add_form}
        return render(request, "dashboard/forms/add_company.html", context)


@admin_only
def add_course(request):
    course_add_form = NewCourseForm()
    if request.method == "POST":
        course_add_form = NewCourseForm(request.POST)
        if course_add_form.is_valid():
            course_add_form.save()
            messages.success(request, "Company has been successfully added.")
            return redirect("dashboard:add_course")
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:add_course")
    else:
        context = {"course_add_form": course_add_form}
        return render(request, "dashboard/forms/add_course.html", context)


@admin_only
def add_new_department(request):
    department_add_form = NewDepartmentForm()
    if request.method == "POST":
        department_add_form = NewDepartmentForm(request.POST)
        if department_add_form.is_valid():
            department_add_form.save()
            messages.success(request, "Department has been successfully added.")
            return redirect("dashboard:add_new_department")
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:add_new_department")
    else:
        context = {"department_add_form": department_add_form}
        return render(request, "dashboard/forms/add_new_department.html", context)


@admin_only
def add_student_to_course(request):
    add_course_student = NewStudentToCourseForm()
    if request.method == "POST":
        add_course_student = NewStudentToCourseForm(request.POST)
        if add_course_student.is_valid():
            add_course_student.save()
            messages.success(request, "Student has been successfully added to the course.")
            return redirect("dashboard:add_student_to_course")
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:add_student_to_course")
    else:
        context = {"add_course_student": add_course_student}
        return render(request, "dashboard/forms/add_student_to_course.html", context)


#####################################################################################
# Queries:
##########

@admin_only
def dashboard_lists(request):
    users = User.objects.all()
    providers = TrainingProvider.objects.all()  # show companies
    courses = Course.objects.all()  # show existing courses
    user_courses = UserCourse.objects.all()  # show registered courses
    departments = Department.objects.all()  # show departments and its students
    context = {"providers": providers, "courses": courses, "user_courses": user_courses, "departments": departments, "users":users}
    return render(request, "dashboard/dash_base.html", context)


@admin_only
def get_company_courses(request, company_name):

training_reg/dashboard/templates/dashboard/dash_base.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid" style="margin-top:60px;">
        <div class="row" >
        <div class="col-lg-1 col-sm-12"></div>
            <div class="col-lg-10 col-sm-12">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">User ID</th>
                      <th scope="col">Full Name</th>
                      <th scope="col">Username</th>
                      <th scope="col">Email Address</th>
                      <th scope="col">Department</th>
                      <th scope="col">Registered Trainings</th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for user in users %}
                    <tr>
                      <th scope="row">{{ user.id }}</th>
                      <td>{{ user.first_name }} {{ user.last_name }} {{ user.family_name }}</td>
                      <td>{{ user.username }}</td>
                      <td>{{ user.email }}</td>
                      <td>{{ user.department }}</td>
                      <td>{{ user.count_trainings }}</td>
                      <td colspan="2"><a class="btn btn-secondary" href="{% url 'dashboard:edit_student_department' student_id=user.id %}">Edit Student</a></td>
                      <td></td>
                    </tr>

                  {% endfor %}
                  </tbody>
                </table>
            </div>
                <div class="col-lg-1 col-sm-12"></div>




    {#    Provider and its courses#}
            <div class="col-lg-5 col-sm-12" style="margin-top: 60px">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Company</th>
                      <th scope="col">Department</th>
                      <th scope="col">Company Courses</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for provider in providers %}
                    <tr>
                      <th scope="row">{{ provider.id }}</th>
                      <td>{{ provider.name }}</td>
                      <td>{{ provider.department.name }}</td>
                      <td><a href="{% url 'dashboard:company_courses' company_name=provider.name %}" class="btn btn-secondary">Show Courses</a></td>
                      <td><a class="btn btn-danger" href="{% url 'dashboard:delete_company' company_name=provider.name %}">Delete Company</a></td>
                    </tr>

                  {% endfor %}
                    <tr>
                      <th scope="row"></th>
                      <td><a class="btn btn-secondary" href="{% url 'dashboard:add_company' %}">Add Company</a></td>
                      <td></td>
                      <td></td>
                      <td></td>
                    </tr>
                  </tbody>
                </table>
            </div>

            <div class="col-lg-2 col-sm-12">

            </div>


{#            Course Details#}
            <div class="col-lg-5 col-sm-12" style="margin-top: 60px">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Course</th>
                      <th scope="col">Company</th>
                      <th scope="col">Status</th>
                      <th scope="col">Period</th>
                      <th scope="col">Start Date</th>
                      <th scope="col">End Date</th>
                      <th scope="col">Details</th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for course in courses %}
                    <tr>
                      <th scope="row">{{ course.id }}</th>
                      <td>{{ course.name }}</td>
                      <td>{{ course.provider }}</td>
                      <td>
                          {% if course.available %}
                              <span class="badge bg-success">Available</span>
                          {% else %}
                              <span class="badge bg-danger">Closed</span>
                          {% endif %}
                      </td>
                        <td>{{ course.period }}</td>
                        <td>{{ course.start_date }}</td>
                        <td>{{ course.end_date }}</td>
                        <td><a class="btn btn-secondary" href="{% url 'dashboard:course_detail' course_name=course.name %}">Show Course</a></td>
                        <td><a class="btn btn-danger" href="{% url 'dashboard:delete_course' course_name=course.name %}">Delete Course</a></td>
                        <td><a class="btn btn-secondary" href="{% url 'dashboard:edit_course' course_name=course.name %}">Edit Course</a></td>
                    </tr>

                  {% endfor %}
                    <tr>
                      <th scope="row"></th>
                      <td colspan="2"><a class="btn btn-secondary" href="{% url 'dashboard:add_course' %}">Add Course</a></td>
                      <td></td><td></td><td></td><td></td><td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                    </tr>
                  </tbody>
                </table>
            </div>


{#        Companies of each department#}
        <div class="col-lg-5 col-sm-12" style="margin-top: 150px">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Department</th>
                      <th scope="col">Companies</th>
                      <th scope="col">Students</th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for department in departments %}
                    <tr>
                      <th scope="row">{{ department.id }}</th>
                      <td>{{ department.name }}</td>
                      <td><a class="btn btn-secondary" href="{% url 'dashboard:get_department_companies' department_name=department.name %}">Show Companies</a></td>
                      <td><a class="btn btn-secondary" href="{% url 'dashboard:get_department_students' department_name=department.name %}">Show Students</a></td>
                      <td><a class="btn btn-danger" href="{% url 'dashboard:delete_department' department_name=department.name %}">Delete Department</a></td>
                      <td><a class="btn btn-secondary" href="{% url 'dashboard:edit_department' department_name=department.name %}">Edit Department</a></td>
                    </tr>
                  {% endfor %}
                  <tr>
                      <td></td>
                      <td><a class="btn btn-secondary" href="{% url 'dashboard:add_new_department' %}">Create Department</a></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                  </tr>
                  </tbody>
                </table>
            </div>


            <div class="col-lg-2 col-sm-12">

            </div>
{#            Registered Courses#}
            <div class="col-lg-5 col-sm-12" style="margin-top: 150px">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Course</th>

                      <th scope="col">Registered Students</th>
                      <th scope="col">Seats Left</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for course in courses %}
                    <tr>
                      <th scope="row">{{ course.id }}</th>
                      <td>{{ course.name }}</td>
                      <td>{{ course.get_course_registered_students }}</td>
                      <td>{{ course.get_course_seats_left }}</td>
                      <td><a class="btn btn-secondary" href="{% url 'dashboard:get_course_registered_students' course_name=course.name %}">Show Students</a></td>
                        {% if course.get_course_seats_left != 0 %}
                      <td><a class="btn btn-secondary" href="{% url 'dashboard:add_student_to_course' %}">Add student</a></td>
                        {% endif %}
                    </tr>
                  {% endfor %}
                  <tr>
                      <td></td>
                      <td><a class="btn btn-secondary" href="{% url 'dashboard:add_student_to_course' %}">Register new student course</a></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                  </tr>
                  </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}