training_reg/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.user_logout, name="logout"),
]

training_reg/dashboard/urls.py
from django.urls import path
from dashboard import views


app_name = "dashboard"

urlpatterns = [
    # Queries Links
    path("dashboard/", views.dashboard_lists, name="dashboard_lists"),
    path("dashboard/<str:company_name>/courses/", views.get_company_courses, name="company_courses"),
    path("dashboard/course/<str:course_name>/", views.get_course_details, name="course_detail"),
    path("dashboard/<str:course_name>/registered_students/", views.get_course_registered_students, name="get_course_registered_students"),
    path("dashboard/training/get_student_training_pass_status/", views.get_student_training_pass_status, name="get_student_training_pass_status"),
    path("dashboard/<str:department_name>/companies/", views.get_department_companies, name="get_department_companies"),
    path("dashboard/<str:department_name>/students/", views.get_department_students, name="get_department_students"),



    # Forms
    path("dashboard/add_company/", views.add_company, name="add_company"),
    path("dashboard/add_course/", views.add_course, name="add_course"),
    path("dashboard/add_new_department/", views.add_new_department, name="add_new_department"),
    path("dashboard/add_student_to_course/", views.add_student_to_course, name="add_student_to_course"),


    # Editing and Deletion

    # Deletion
    path("dashboard/company/<str:company_name>/delete/", views.delete_company, name="delete_company"),
    path("dashboard/course/<str:course_name>/delete/", views.delete_course, name="delete_course"),
    path("dashboard/department/<str:department_name>/delete/", views.delete_department, name="delete_department"),
    path("dashboard/student_course/<int:student_id>/<str:course_name>/delete/", views.delete_student_from_course, name="delete_student_from_course"),

    # Editing
    path("dashboard/course/<str:course_name>/edit/", views.edit_course, name="edit_course"),
    path("dashboard/department/<str:department_name>/edit/", views.edit_department, name="edit_department"),
    path("dashboard/student_course/<int:student_id>/<str:course_name>/edit/", views.edit_student_course, name="edit_student_course"),
    path("dashboard/department/student/<int:student_id>/edit/", views.edit_student_department, name="edit_student_department"),


]

training_reg/training_reg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("training.urls", namespace="training")),
    path("", include("dashboard.urls", namespace="dashboard")),
]

training_reg/dashboard/models.py
from django.db import models

# Create your models here.

training_reg/dashboard/forms.py
from django import forms
from accounts.models import *
from training.models import *
from django.conf import settings

class NewCompanyForm(forms.ModelForm):
    class Meta:
        model = TrainingProvider
        fields = "__all__"

class NewCourseForm(forms.ModelForm):
    start_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.SelectDateWidget)
    end_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, widget=forms.SelectDateWidget)
    class Meta:
        model = Course
        exclude = ["student_numbers"]

class NewStudentToCourseForm(forms.ModelForm):
    class Meta:
        model = UserCourse
        fields = "__all__"

class NewDepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ["name"]

class EditStudentDepartmentForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "family_name", "username", "department", "count_trainings"]

training_reg/dashboard/views.py
from django.shortcuts import render, redirect
from training.models import *
from accounts.models import *
import json
from django.http import JsonResponse
from dashboard.forms import *
from django.contrib import messages
from dashboard.decorators import admin_only


# Create your views here.


################################################################################
# Data Editing and Deletion
############################

# Deletion
@admin_only
def delete_company(request, company_name):
    if request.method == "POST":
        company = TrainingProvider.objects.get(name__icontains=company_name)
        company.delete()
        return redirect("dashboard:dashboard_lists")
    else:
        context = {"company_name": company_name}
        return render(request, "dashboard/Data_Edit_Deletion/delete_company.html", context)


@admin_only
def delete_course(request, course_name):
    if request.method == "POST":
        course = Course.objects.get(name__icontains=course_name)
        course.delete()
        return redirect("dashboard:dashboard_lists")
    else:
        context = {"course_name": course_name}
        return render(request, "dashboard/Data_Edit_Deletion/delete_course.html", context)


@admin_only
def delete_department(request, department_name):
    if request.method == "POST":
        department = Department.objects.get(name__icontains=department_name)
        department.delete()
        return redirect("dashboard:dashboard_lists")
    else:
        context = {"department_name": department_name}
        return render(request, "dashboard/Data_Edit_Deletion/delete_department.html", context)


@admin_only
def delete_student_from_course(request, student_id, course_name):
    student = User.objects.get(id=student_id)
    if request.method == "POST":
        the_course = Course.objects.get(name__icontains=course_name)
        student_in_this_course = UserCourse.objects.get(user=student, course=the_course)
        student_in_this_course.delete()
        return redirect("dashboard:dashboard_lists")
    else:
        context = {"student_name": student.first_name + " " + student.last_name + " " + student.family_name,
                   "course_name": course_name}
        return render(request, "dashboard/Data_Edit_Deletion/delete_student_from_course.html", context)


# Edition
@admin_only
def edit_course(request, course_name):
    course = Course.objects.get(name__icontains=course_name)
    edit_course_form = NewCourseForm(instance=course)
    if request.method == "POST":
        edit_course_form = NewCourseForm(request.POST, instance=course)
        if edit_course_form.is_valid():
            edit_course_form.save()
            messages.success(request, "Course details have been successfully updated.")
            return redirect("dashboard:course_detail", course_name=course_name)
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:add_company")
    else:
        context = {"edit_course_form": edit_course_form, "course_name": course_name}
        return render(request, "dashboard/Data_Edit_Deletion/edit_course.html", context)


@admin_only
def edit_department(request, department_name):
    department = Department.objects.get(name__icontains=department_name)
    edit_department_form = NewDepartmentForm(instance=department)
    if request.method == "POST":
        edit_department_form = NewDepartmentForm(request.POST, instance=department)
        if edit_department_form.is_valid():
            edit_department_form.save()
            messages.success(request, "Course details have been successfully updated.")
            return redirect("dashboard:edit_department", department_name=department_name)
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("/")
    else:
        context = {"edit_department_form": edit_department_form, "department_name": department_name}
        return render(request, "dashboard/Data_Edit_Deletion/edit_department.html", context)


@admin_only
def edit_student_course(request, student_id, course_name):
    student = User.objects.get(id=student_id)
    course = Course.objects.get(name__icontains=course_name)
    student_course = UserCourse.objects.get(user=student, course=course)
    student_course_form = NewStudentToCourseForm(instance=student_course)
    if request.method == "POST":
        student_course_form = NewStudentToCourseForm(request.POST, instance=student_course)
        if student_course_form.is_valid():
            student_course_form.save()
            messages.success(request, "Course details have been successfully updated.")
            return redirect("dashboard:get_course_registered_students", course_name=course_name)
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:get_course_registered_students", course_name=course_name)
    else:
        context = {"student_course_form": student_course_form,
                   "student_name": student.first_name + " " + student.last_name + " " + student.family_name,
                   "course_name": course_name}
        return render(request, "dashboard/Data_Edit_Deletion/edit_student_course.html", context)


@admin_only
def edit_student_department(request, student_id):
    student = User.objects.get(id=student_id)
    user_department_form = EditStudentDepartmentForm(instance=student)
    if request.method == "POST":
        user_department_form = EditStudentDepartmentForm(request.POST, instance=student)
        if user_department_form.is_valid():
            user_department_form.save()
            messages.success(request, "Student data have been successfully updated.")
            return redirect("dashboard:dashboard_lists")
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:dashboard_lists")

    else:
        context = {"user_department_form": user_department_form,
                   "student_name": student.first_name + " " + student.last_name + " " + student.family_name}
        return render(request, "dashboard/Data_Edit_Deletion/edit_user_department.html", context)


##################################################################################
# Creation Forms:
#################
@admin_only
def add_company(request):
    company_add_form = NewCompanyForm()
    if request.method == "POST":
        company_add_form = NewCompanyForm(request.POST)
        if company_add_form.is_valid():
            company_add_form.save()
            messages.success(request, "Company has been successfully added.")
            return redirect("dashboard:add_company")
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:add_company")
    else:
        context = {"company_add_form": company_add_form}
        return render(request, "dashboard/forms/add_company.html", context)


@admin_only
def add_course(request):
    course_add_form = NewCourseForm()
    if request.method == "POST":
        course_add_form = NewCourseForm(request.POST)
        if course_add_form.is_valid():
            course_add_form.save()
            messages.success(request, "Company has been successfully added.")
            return redirect("dashboard:add_course")
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:add_course")
    else:
        context = {"course_add_form": course_add_form}
        return render(request, "dashboard/forms/add_course.html", context)


@admin_only
def add_new_department(request):
    department_add_form = NewDepartmentForm()
    if request.method == "POST":
        department_add_form = NewDepartmentForm(request.POST)
        if department_add_form.is_valid():
            department_add_form.save()
            messages.success(request, "Department has been successfully added.")
            return redirect("dashboard:add_new_department")
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:add_new_department")
    else:
        context = {"department_add_form": department_add_form}
        return render(request, "dashboard/forms/add_new_department.html", context)


@admin_only
def add_student_to_course(request):
    add_course_student = NewStudentToCourseForm()
    if request.method == "POST":
        add_course_student = NewStudentToCourseForm(request.POST)
        if add_course_student.is_valid():
            add_course_student.save()
            messages.success(request, "Student has been successfully added to the course.")
            return redirect("dashboard:add_student_to_course")
        else:
            messages.error(request, "Error Occurred, Make sure you filled all fields.")
            return redirect("dashboard:add_student_to_course")
    else:
        context = {"add_course_student": add_course_student}
        return render(request, "dashboard/forms/add_student_to_course.html", context)


#####################################################################################
# Queries:
##########

@admin_only
def dashboard_lists(request):
    users = User.objects.all()
    providers = TrainingProvider.objects.all()  # show companies
    courses = Course.objects.all()  # show existing courses
    user_courses = UserCourse.objects.all()  # show registered courses
    departments = Department.objects.all()  # show departments and its students
    context = {"providers": providers, "courses": courses, "user_courses": user_courses, "departments": departments, "users":users}
    return render(request, "dashboard/dash_base.html", context)


@admin_only
def get_company_courses(request, company_name):

training_reg/dashboard/templates/dashboard/selections/company_courses.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Course</th>
                      <th scope="col">Company</th>
                      <th scope="col">Status</th>
                      <th scope="col">Period</th>
                      <th scope="col">Start Date</th>
                      <th scope="col">End Date</th>
                      <th scope="col">Details</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for company_course in company_courses %}
                    <tr>
                      <th scope="row">{{ company_course.id }}</th>
                      <td>{{ company_course.name }}</td>
                      <td>{{ company_course.provider }}</td>
                      <td>
                          {% if company_course.available %}
                              <span class="badge bg-success">Available</span>
                          {% else %}
                              <span class="badge bg-danger">Closed</span>
                          {% endif %}
                      </td>
                        <td>{{ company_course.period }}</td>
                        <td>{{ company_course.start_date }}</td>
                        <td>{{ company_course.end_date }}</td>
                        <td><a class="btn btn-secondary" href="{% url 'dashboard:course_detail' course_name=company_course.name %}">Show Course</a></td>
                    </tr>

                  {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

training_reg/dashboard/templates/dashboard/selections/course_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
    </style>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3">

            </div>
            <div class="col-sm-6 course_detail">
                <h1 style="padding:10px;text-align: center;border-bottom: 1px solid;border-top: 1px solid">{{ course.name }}</h1>
                <br><br><br>
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Company</th>
                      <th scope="col">Status</th>
                      <th scope="col">Period</th>
                      <th scope="col">Start Date</th>
                      <th scope="col">End Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">{{ course.id }}</th>
                      <td>{{ course.provider }}</td>
                      <td>
                          {% if course.available %}
                              <span class="badge bg-success">Available</span>
                          {% else %}
                              <span class="badge bg-danger">Closed</span>
                          {% endif %}
                      </td>
                        <td>{{ course.period }}</td>
                        <td>{{ course.start_date }}</td>
                        <td>{{ course.end_date }}</td>
                    </tr>

                  </tbody>
                </table>
                <p class="text-center">
                  <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Show Brief
                  </button>
                </p>
                <div class="collapse" id="collapseExample">
                  <div class="card card-body" style="text-align: left">
                        <pre>{{ course.brief }}</pre>
                  </div>
                </div>
            </div>
            <div class="col-sm-3">

            </div>
        </div>
    </div>
{% endblock %}

training_reg/dashboard/templates/dashboard/selections/course_registered_students.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        #header{
            text-align: center;
            margin:10px;
            padding: 10px;
            border-bottom: 1px solid darkred;
            border-top: 1px solid darkred;
        }
    </style>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-1">

            </div>
            <div class="col-sm-8 course_detail">
            <h1 id="header">{{ course_name }} </h1>
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Full Name</th>
                      <th scope="col">Username</th>
                      <th scope="col">Email Address</th>
                      <th scope="col">Registered Courses</th>
                      <th scope="col">Pass Status</th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for user_course in user_courses %}
                    <tr>
                      <th scope="row">{{ user_course.user.id }}</th>
                      <td>{{ user_course.user.first_name }} {{ user_course.user.last_name }} {{ user_course.user.family_name }}</td>
                      <td>{{ user_course.user.username }}</td>
                      <td>{{ user_course.user.email }}</td>
                      <td>{{ user_course.user.count_trainings }}</td>
                      <td colspan="3" id="status{{ user_course.user.id }}"><button class="btn btn-secondary" onclick="get_student_training_status('{{ course_name }}', '{{ user_course.user.id }}')">Pass Status</button></td>
                      <td colspan="4"><a class="btn btn-danger" href="{% url 'dashboard:delete_student_from_course' student_id=user_course.user.id course_name=course_name %}">Delete Student Course</a></td>
                      <td colspan="4"><a class="btn btn-secondary" href="{% url 'dashboard:edit_student_course' student_id=user_course.user.id course_name=course_name %}">Edit Student Course</a></td>
                     </tr>
                    {% endfor %}
                  <tr>
                      <td></td><td colspan="2"><a href="{% url 'dashboard:add_student_to_course' %}" class="btn btn-secondary">Add Student</a></td><td></td><td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                  </tr>
                  </tbody>
                </table>
            </div>
            <div class="col-sm-1">

            </div>
        </div>
    </div>
    <script>
    function get_student_training_status(course_name, user_id){
        console.log(course_name, user_id)
        let url = "../../training/get_student_training_pass_status/";
        fetch(url, {
            method: "POST",
            headers: {
                "Content-type": "application/json",
                "X-CSRFToken": csrftoken,
            },
            body: JSON.stringify({"course_name":course_name, "user_id":user_id}),
        })
        .then((response) => {
            return response.json();
        })
        .then((data) => {
            console.log(`Data: ${data}`);
            let status = document.getElementById(`status${user_id}`);
            if(data == true){
                status.innerHTML = `
                    <span class="badge rounded-pill bg-success">Passed</span>
                `
            }
            else if(data == false){
                status.innerHTML = `
                    <span class="badge rounded-pill bg-danger">Failed</span>
                `
            }
            else if(data == null){
                status.innerHTML = `
                    <span class="badge rounded-pill bg-warning">Awaiting Evaluation</span>
                `
            }
        })
    }

    </script>
{% endblock %}

training_reg/dashboard/templates/dashboard/selections/department_companies.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        #header{
            text-align: center;
            margin:10px;
            padding: 10px;
            border-bottom: 1px solid darkred;
            border-top: 1px solid darkred;
        }
    </style>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3">

            </div>
            <div class="col-sm-5 course_detail">
            <h1 id="header">{{ department_name }} Department</h1>
                <table class="table">
                  <thead>
                    <tr>
                      <th colspan="2" scope="col">ID</th>
                      <th colspan="2" scope="col">Company</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for company in companies %}
                    <tr>
                      <th colspan="2"  scope="row">{{ company.id }}</th>
                      <td colspan="2" >{{ company.name }}</td>
                    </tr>
                    {% endfor %}
                  <tr>
                      <td ></td>
                      <td colspan="2" ><a href="{% url 'dashboard:add_company' %}" class="btn btn-secondary">Add Company</a></td>
                  </tr>
                  </tbody>
                </table>
            </div>
            <div class="col-sm-3">

            </div>
        </div>
    </div>
{% endblock %}

training_reg/dashboard/templates/dashboard/selections/department_students.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        #header{
            text-align: center;
            margin:10px;
            padding: 10px;
            border-bottom: 1px solid darkred;
            border-top: 1px solid darkred;
        }
    </style>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3">

            </div>
            <div class="col-sm-5 course_detail">
            <h1 id="header">{{ department_name }} Department</h1>
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Full Name</th>
                      <th scope="col">Username</th>
                      <th scope="col">Email Address</th>
                      <th scope="col">Registered Courses</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for student in students %}
                    <tr>
                      <th scope="row">{{ student.id }}</th>
                      <td>{{ student.first_name }} {{ student.last_name }} {{ student.family_name }}</td>
                      <td>{{ student.username }}</td>
                      <td>{{ student.email }}</td>
                      <td>{{ student.count_trainings }}</td>
                      <td><a href="{% url 'dashboard:edit_student_department' student_id=student.id %}" class="btn btn-secondary">Edit Student Department</a></td>
                    </tr>
                    {% endfor %}

                  </tbody>
                </table>
            </div>
            <div class="col-sm-3">

            </div>
        </div>
    </div>
{% endblock %}